### PR TITLE
fixing problems with phpunit version and stale dependencies

### PR DESCRIPTION
**Pull request by biganfa**
fixed two tiny problems
1. phpunit version downloaded via ansible by default is now 6.0, it has breaking changes so tests do not work with it. I forced phpunit version to be latest 5.*
2. updated composer.lock file, because the demo application has errors with stale versions of broadway/broadway-bundle and broadway/broadway-event-dbal packages. Updating dependencies fixes the trouble.

### CODE REVIEW

**Comment by wjzijderveld** [comment]
Thanks!

Any idea what causes the failures on PHP7? I haven't seen those kind of errors before.

**Comment by othillo** [comment]
I noticed the same errors before merging https://github.com/broadway/broadway-demo/pull/25.

When I ran Travis on master (before merge) even master was broken.

I suggest merging this and investigate the error separately.

**Comment by biganfa** [comment]
@othillo  @wjzijderveld i think the reason of travis fails with PHP7 is a version of phpunit. We can see in travis logs that for php5.7 it uses phpunit version 5, and for php7 it uses phpunit6 (not sure why?), but phpunit 6 has breaking changes and it is completely incompatible with the test suite. Exactly this problem is fixed in playbook.yml so it downloads phpunit 5.7 into vagrant box. 

so, the solution may be somehow forsing phpunit 5.7 for travis everythime.

**Comment by othillo** [comment]
@biganfa thanks for investigating. I created a fix/workaround here: https://github.com/broadway/broadway-demo/pull/27

**Comment by wjzijderveld** [comment]
Thanks @biganfa

**Pull request merged**
